gcloud sdb case handling

diff --git a/bin/gcloud_sdb b/bin/gcloud_sdb
--- a/bin/gcloud_sdb
+++ b/bin/gcloud_sdb
@@ -1,13 +1,33 @@
 #!/bin/sh
 # Usage: curl -s https://raw.githubusercontent.com/rockstat/bootstrap/master/bin/gcloud_sdb | sudo bash -
 
-set -ex
+set -e
 
-mkfs.ext4 -m 0 -F -E lazy_itable_init=0,lazy_journal_init=0,discard /dev/sdb
-mount -o discard,defaults /dev/sdb /srv
-cp /etc/fstab /etc/fstab.backup
-SDBID=`blkid /dev/sdb |  cut -d' ' -f2 | cut -d\" -f2`
-echo -e "UUID=$SDBID /srv ext4 discard,defaults,nofail 0 2\n" >> /etc/fstab
-chmod a+w /srv
+
+DISK=/dev/sdb
+
+
+if [ ! -e $DISK ] ; then
+    echo "Device $DISK not exists. Break."
+    exit 1
+fi
+
+SDBID=`blkid $DISK |  cut -d' ' -f2 | cut -d\" -f2`
+
+if grep $DISK /etc/mtab > /dev/null 2>&1; then
+    echo "Disk already mounted."
+else
+    mkfs.ext4 -m 0 -F -E lazy_itable_init=0,lazy_journal_init=0,discard $DISK
+    chmod a+w /srv
+fi
+
+
+if grep $SDBID /etc/fstab > /dev/null 2>&1; then
+    echo "Record already in fstab."
+else
+    cp /etc/fstab /etc/fstab.backup
+    echo -e "UUID=$SDBID /srv ext4 discard,defaults,nofail 0 2\n" >> /etc/fstab
+fi
+
 
 echo "Done!"
